import 'package:cloud_firestore/cloud_firestore.dart';
class EducationalChatService { EducationalChatService(this._db); final FirebaseFirestore _db;
 Stream<QuerySnapshot<Map<String,dynamic>>> messages(String conversationId)=>_db.collection('conversations').doc(conversationId).collection('messages').orderBy('createdAt').snapshots();
 Future<void> sendText({required String conversationId,required String senderId,required String text,String? replyTo}) async { final ref=_db.collection('conversations').doc(conversationId); final message=ref.collection('messages').doc(); final batch=_db.batch(); batch.set(message,{'senderId':senderId,'type':'text','text':text,'replyTo':replyTo,'deliveredTo':[],'readBy':[],'createdAt':FieldValue.serverTimestamp()}); batch.set(ref,{'lastMessage':text,'lastMessageAt':FieldValue.serverTimestamp(),'typingUserIds':FieldValue.arrayRemove([senderId])},SetOptions(merge:true)); await batch.commit(); }
 Future<void> setTyping(String conversationId,String userId,bool value)=>_db.collection('conversations').doc(conversationId).update({'typingUserIds':value?FieldValue.arrayUnion([userId]):FieldValue.arrayRemove([userId])});
 Future<void> markRead(String conversationId,String messageId,String userId)=>_db.collection('conversations').doc(conversationId).collection('messages').doc(messageId).update({'readBy':FieldValue.arrayUnion([userId])});
 Future<void> deleteOwnMessage(String conversationId,String messageId)=>_db.collection('conversations').doc(conversationId).collection('messages').doc(messageId).update({'deletedAt':FieldValue.serverTimestamp(),'text':'تم حذف هذه الرسالة'});
 Future<void> toggleReaction(String conversationId,String messageId,String userId,String emoji)=>_db.runTransaction((tx) async {final ref=_db.collection('conversations').doc(conversationId).collection('messages').doc(messageId);final data=(await tx.get(ref)).data()??{};final reactions=Map<String,dynamic>.from(data['reactions']??{});reactions[userId]=reactions[userId]==emoji?null:emoji;reactions.removeWhere((_,v)=>v==null);tx.update(ref,{'reactions':reactions});});
}
