// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn-2YQ78EX_jkdMvIkO7tZKKbqra6nujA',
    appId: '1:660683513871:android:e99d97794199911ef5437a',
    messagingSenderId: '660683513871',
    projectId: 'housingalsaai',
    storageBucket: 'housingalsaai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX4pE7oXuWKfI9KInHXHymuXVfnJXI8Fo',
    appId: '1:660683513871:ios:f98c63e629f2fb78f5437a',
    messagingSenderId: '660683513871',
    projectId: 'housingalsaai',
    storageBucket: 'housingalsaai.appspot.com',
    androidClientId: '660683513871-a8namehu2bukslsk82rksismj6nll019.apps.googleusercontent.com',
    iosClientId: '660683513871-oceahbdgb5pb1i5jaqtju8kdu2v1j4cj.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled2',
  );
}
